### ISSUE TITLE
Needs browserifying and making into a node package

### ISSUE THREAD

**Issue by hikari-no-yume** [TazeTSchnitzel/Firth#15]
This way it can be used from the CLI and have nice stuff like [unit tests](https://github.com/TazeTSchnitzel/Firth/issues/16).

**Comment by mathroc** [comment]
What would be the public API ? I think we should be able to execute a whole program but also be able to build REPL

``` js
module.exports = {
    compile: function(source) {
        [snip]
        return opcodes;
    },
    execute: function(opcodes, scope) {
        if (scope === undefined) {
            scope = require('./stdlib);
        }
        [snip]
        return scope;
    },
};
```

would something like that be enough ?

**Comment by hikari-no-yume** [comment]
`test.html` already relies on the lexer, parser and interpreter being exposed, so it'd probably have all of those.

**Comment by mathroc** [comment]
Correct, without the lexer output we couldn't have the same information currently presents in `test.html`.

Would you be ok to return promise ? it would make it easier to, later, maybe, use WebWorkers to do the heavy work

**Comment by hikari-no-yume** [comment]
That could be done as and when it's needed.
