### ISSUE TITLE
Use function name/body in pretty-prints

### ISSUE THREAD

**Issue by hikari-no-yume** [TazeTSchnitzel/Firth#23]
We now have pretty-printing since this commit: https://github.com/TazeTSchnitzel/Firth/commit/1e346e7fd067982421ca46f59ebdd99e8056f98a

But `add show.` is just `[<internal>]` and `[1 add.] show.` is just `[<user>]`. This could be improved by showing, for example, the name of the function.

**Comment by mathroc** [comment]
This one can be closed I think

**Comment by hikari-no-yume** [comment]
Oh, yes. You fixed it. :)
